### ISSUE TITLE
No `index.js` on root directory of release branch.

### ISSUE THREAD

**Issue by a-y-u-s-h** [rehooks/online-status#11]
I was getting this `Module not found: Error: Can't resolve '@rehooks/online-status'` error when importing something from "@rehooks/online-status" after I updated my dependencies. Upon inspection, I saw that there's no index.js in root, but it's inside src/. 

![2019-05-04_01-16-22_screenshot](https://user-images.githubusercontent.com/19586719/57161977-89ac2780-6e0a-11e9-964d-281db6ec7e87.png)

I made a quickfix by putting it in its root folder to make it work temporarily. Please fix the released version. It'll cause the trouble to fix it manually after updates.

**Comment by mathdroid** [comment]
On it.

**Comment by mathdroid** [comment]
Fixed in `1.1.2` https://github.com/rehooks/online-status/releases/tag/v1.1.2

Thanks @a-y-u-s-h !
